/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  skill: [
    'skill/introduction',
    
    {
        label: 'FOC',
        type: 'category',
        link: {
          type: 'generated-index',
        },
        items: [
          'skill/motor/pmsm/pmsm_motor',
        ],
    },
    {
      label: 'FFT',
      type: 'category',
      link: {
      type: 'generated-index',
      },
      items: [
        'skill/motor/pmsm/pmsm_motor',
          ]        
     },
     {
      label: 'DSP',
      type: 'category',
      link: {
      type: 'generated-index',
      },
      items: [
/*         'skill/dsp/not', */
          ]        
     },
     {
      label: 'Liunx',
      type: 'category',
      link: {
      type: 'generated-index',
      },
      items: [
        'skill/motor/pmsm/pmsm_motor',
          ]        
     },
     {
      label: 'FPGA',
      type: 'category',
      link: {
      type: 'generated-index',
      },
      items: [
        'skill/motor/pmsm/pmsm_motor',
          ]        
     },

    {
      label: '硬件基础',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          label: '元器件基础',
          type: 'category',
          link: {
          type: 'generated-index',
          },
          items: [
            'skill/hardware/component/Res',
            'skill/hardware/component/Cap',
            'skill/hardware/component/MOS',
            ]        
         },
         {
          label: '常用电路分析',
          type: 'category',
          link: {
          type: 'generated-index',
          },
          items: [
            'skill/motor/pmsm/pmsm_motor',
              ]        
         },
      ]
    },
    {
      label: '电机控制',
      type: 'category',
      link: {
      type: 'generated-index',
      },
      items: [
          'skill/motor/pmsm/pmsm_motor',
          ]        
     },
    {
      label: '杂项',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/other',
        }, 
      ],
    },
  ],



  tools: [
    'tools/introduction',
    'tools/everything-quick-search-local-files',
    'tools/windows-custom-right-click-menu',
    'tools/windows-terminal-beautify',
    'tools/vscode-config',
  ],


  project_group: [
    'project_group/introduction',
    {
      label: '电机控制',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          label: 'AxDrive-L',
          type: 'category',
          link: {
          type: 'generated-index',
          },
          items: [
            'project_group/motor_ctrl/AxDrive-L/AxDrive-L_user_manual',
            'project_group/motor_ctrl/AxDrive-L/AxDrive-L_hardware_design_report',
            'project_group/motor_ctrl/AxDrive-L/AxDrive-L_software_design_report',
            
          ]
        },
      ],
  },
  ],
}

module.exports = sidebars
